services:
  mongodb:
    image: 'mongo:latest'
    env_file:
        - mongodb.env
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    env_file:
        - mongoexpress.env
    ports:
      - 8081:8081
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    env_file:
        - minio.env
    volumes:
      - ~/Util/Storage:/data
    ports:
      - 9000:9000
      - 9001:9001
